"""Add sender_wallet_id and other fields to transactions

Revision ID: e6174c61f2a3
Revises: fbf01adbfb68
Create Date: 2025-06-12 15:02:50.347131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6174c61f2a3'
down_revision: Union[str, None] = 'fbf01adbfb68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('sender_wallet_id', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('receiver_wallet_id', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('transaction_type', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('status', sa.String(), nullable=True))
    op.drop_index(op.f('ix_transactions_receiver_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_sender_id'), table_name='transactions')
    op.create_index(op.f('ix_transactions_receiver_wallet_id'), 'transactions', ['receiver_wallet_id'], unique=False)
    op.create_index(op.f('ix_transactions_sender_wallet_id'), 'transactions', ['sender_wallet_id'], unique=False)
    op.drop_constraint(op.f('transactions_receiver_id_fkey'), 'transactions', type_='foreignkey')
    op.drop_constraint(op.f('transactions_sender_id_fkey'), 'transactions', type_='foreignkey')
    op.create_foreign_key(None, 'transactions', 'users', ['receiver_wallet_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'users', ['sender_wallet_id'], ['id'])
    op.drop_column('transactions', 'sender_id')
    op.drop_column('transactions', 'receiver_id')
    op.drop_constraint(op.f('unique_user_wallet'), 'wallets', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('unique_user_wallet'), 'wallets', ['user_id'])
    op.add_column('transactions', sa.Column('receiver_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('transactions', sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.create_foreign_key(op.f('transactions_sender_id_fkey'), 'transactions', 'users', ['sender_id'], ['id'])
    op.create_foreign_key(op.f('transactions_receiver_id_fkey'), 'transactions', 'users', ['receiver_id'], ['id'])
    op.drop_index(op.f('ix_transactions_sender_wallet_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_receiver_wallet_id'), table_name='transactions')
    op.create_index(op.f('ix_transactions_sender_id'), 'transactions', ['sender_id'], unique=False)
    op.create_index(op.f('ix_transactions_receiver_id'), 'transactions', ['receiver_id'], unique=False)
    op.drop_column('transactions', 'status')
    op.drop_column('transactions', 'transaction_type')
    op.drop_column('transactions', 'receiver_wallet_id')
    op.drop_column('transactions', 'sender_wallet_id')
    # ### end Alembic commands ###
